version: 2

updates:
  - package-ecosystem: "npm"
    cooldown:
      default-days: 7
    versioning-strategy: increase
    directories:
      - "/"
      - "/packages/app"
      - "/packages/cli"
      - "/packages/cloud"
      - "/packages/commons"
      - "/packages/commons-server"
      - "/packages/serverless"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "express"
        # Ignore new versions for 5.x
        versions: ["5.x"]
      - dependency-name: "*"
        # Ignore all major updates
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
