blank_issues_enabled: false
contact_links:
  - name: Community support
    url: https://github.com/mockoon/mockoon/discussions
    about: Please ask and answer questions here.
  - name: Enterprise support
    url: https://mockoon.com/pro/
    about: Get enterprise grade support
  - name: Discord server
    url: https://discord.com/invite/JmTBk59MTb
    about: Join us to chat with the community and the team.
