name: New discussion auto reply

# Disable all permissions by default
permissions: {}

on:
  discussion:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Generate an app token
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}
          permissions: discussions:write
      - name: Extract discussion create event JSON
        id: read-event
        run: |
          echo "discussionId=$(node -e 'console.log(require(process.env.GITHUB_EVENT_PATH).discussion.node_id)')" >> "$GITHUB_OUTPUT"
      - name: Write body into an output
        run: |
          echo "{\"query\":\"mutation { addDiscussionComment(input: { discussionId: \\\"${{ steps.read-event.outputs.discussionId }}\\\", body: \\\"\\\"\\\"### Thank you for reaching out! ðŸ‘‹\\n\\nWe appreciate you taking the time to ask your question or report an issue. Please note that response times may vary as we work through requests. We\\\'ll get back to you as soon as possible.\\n\\nIf you require priority support or enterprise assistance, you can explore our support options on [mockoon.com](https://mockoon.com/pricing/).\\n\\nAlternatively, for a guaranteed fast response (usually within a day), you can [purchase a one-time support request](https://github.com/sponsors/mockoon?frequency=one-time), or choose one of our [sponsorship tiers](https://github.com/sponsors/mockoon?frequency=recurring) including support on GitHub Sponsors.\\n\\nThank you for your patience and for being part of the Mockoon community!\\\"\\\"\\\" }) { comment { id body createdAt author { login } } } }\"}" >> ./body.json
          cat ./body.json
      - name: Add a welcome comment to the discussion
        run: |
          curl -X POST -H "Authorization: bearer ${{ steps.generate-token.outputs.token }}" -H "Content-Type: application/json" -d @./body.json https://api.github.com/graphql
